#!/bin/sh
# md-tree!
sed -i '/\# Project tree/Q' README.md
tree=$(tree -tf --noreport -I '*~' --charset ascii $1 |
       sed -e 's/| \+/  /g' -e 's/[|`]-\+/ */g' -e 's:\(* \)\(\(.*/\)\([^/]\+\)\):\1[\4](\2):g')
countDirs=$(find . -type d -not -path "*/.git/*" | wc -l)
countDirs=$(($countDirs-1))
countFile=$(find . -type f -not -path "*/.git/*" | wc -l)
countFile=$(($countFile-1))
countAll=$(($countDirs+$countFile))
mddir > /dev/null
sed -i "is/^/\`\`\`\n/" directoryList.md 
printf "\`\`\`" >> directoryList.md
printf "# Project tree\n\n${tree}\n" >> README.md
printf "\n\n### Files: ${countFile}, Directorys: ${countDirs}, both: ${countAll}\n" >> README.md

printf "\n\n Full list at [directoryList.md](./directoryList.md)" >> README.md
git add .
